---
title: "NEWS"
author: "R. Mark Sharp"
date: "01/07/2020"
output:
   github_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# nprcgenekeepr 0.5.42.9003
-   Renamed local and remote repositories from nprcmanager to nprcgenekeepr.

# nprcgenekeepr 0.5.42.9002
-   Changed name of package to nprcgenekeepr. This required changing of many
    of the supporting files and functions. Having good unit test coverage of the
    functions (739 test with > 90 percent coverage) made this possible.
-   This is the last version under the nprcmanager repository name.
-   Running the build check had OK: 739; Failed: 0; Warnings: 0; Skipped: 0

# nprcmanager 0.5.42.9001
-   Adding small executable examples in `roxygen2` comments that will go into 
    the Rd-files. Since I have tests, I am wrapping the examples in \donttest{}.
-   Added code prior to changing `par()` in _getPyramidPlot.R_ to reset `par()` 
    with   
    `opar <- par(no.readonly =TRUE)`  
    `on.exit(par(opar))`   
-   Removed the word "Implements" from the title. 
-   Reworded the first sentence of the Description element and therein removing
    "implements" and "nprcmanager" as unnecessary words.
-   Added single quotes around all package, software, and API names within the
    Description element of the DESCRIPTION file.
    
# nprcmanager 0.5.42.9000
-   Added ability to export genetic summary statistic plots

# nprcmanager 0.5.42 (20191208)
-   CRAN submission
-   Move output of suspicious parent list from the user's home directory to
    the result of `tempdir()`.

# nprcmanager 0.5.41 (20191130)
-   CRAN submission.
    
# nprcmanager 0.5.40.9002 (20191119)
-   Tried to get vignette for shiny application to find images on all building
    platforms by adding "./" to relative path.

# nprcmanager 0.5.40.9001 (20191115)
-   Added unit test for __create_wkbk__ from github.com/rmsharp/rmsutilityr
-   Fixed bug in Genetic Value Analysis tab were failure to remove all white
    space in Filter View Id window did not clear filter.
-   Changed minimum parent age default from 4 to 2 years.
-   Added ability to download founders in a _maleFounders.csv_ file and a 
    _femaleFounders.csv_ file.
-   Added __createExampleFiles__ and __saveDataframesAsFiles__ to allow
    the user to generate all of the example pedigrees and other files used in 
    testing and in tutorials.
-   Removed __Development_Plans.Rmd__ from build because it has be replaced
    by adding issues on our issue tracker at 
    [github.com/rmsharp/nprcmanager/issues](
    https://github.com/rmsharp/nprcmanager/issues).

# nprcmanager 0.5.40.9000 (20191115) 
-   Corrected bug in __addIdRecords__ to handle _NA_ characters; amended its
    unit tests to check for correct behavior
-   Changed name of __sexRatioWithAddions__ to __getSexRatioWithAdditions__

# nprcmanager 0.5.39 (20191115)
-   Moved vignettes to expose them in GitHub Pages.
-   Removed more unneeded files from package.

# nprcmanager 0.5.38 (20191113)
-   Changed __getBreederPed__ function to __getFocalAnimalPed__ and animals
    read in by that function from __breeders__ to __focalAnimals__

# nprcmanager 0.5.37 (20191108)
-   Working on updating documentation

# nprcmanager 0.5.36 (20191106)
-   Added colorIndex to list returned by getIndianOriginStatus(),
    getProductionStatus(), and getProportionLow(). Updated related unit tests
-   Changed getSiteInfo() to reflect ONPRCs query structure
-   Changed .Rbuildignore to leave out .png image files needed for Shiny 
    tutorial.
    
# nprcmanager 0.5.35 (20191013)
-   Corrected calculateSexRatio and updated unit test
-   Modified getProductionStatus to match new definition and added unit tests

# nprcmanager 0.5.34 (20191006)
-   Added code to filter out animals no longer at institution and without birth date.

# nprcmanager 0.5.33 (20191006)
-   Broke up LICENSE contents into LICENSE and LICENSE.md for CRAN compliance

# nprcmanager 0.5.32 (20191004)
-   Corrected ancestry to sexCodes in test_convertSexCodes()

# nprcmanager 0.5.31 (20191003)
-   Added more tutorial notes
-   Removed undefined elements in DESCRIPTION file including 
    Displaymode: Showcase, which is recommended in a Shiny example by RStudio.
    This was removed based on RHUB feedback.
-   Added more code for genetic diversity dashboard.

# nprcmanager 0.5.30 (20190829)
-   Began adding code for the genetic diversity dashboard. This includes the 
    functions 
    __getIndianOriginStatus__ and __getProportionLow__, and a rudimentary
    __makeGeneticDiversityDashboard__ function.
-   Added another obfuscation function __mapIdsToObfuscated__ to further 
    facilitate creation of obfuscated data. This was specifically used to 
    obfuscate haplotype data Ids.
    
# nprcmanager 0.5.29 (20190810)
-   Copied rmsutilityr functions into nprcmanager to make Publication on the
    RStudio Shiny application hosting site possible

# nprcmanager 0.5.28 (20190714)
-   Added to interactive tutorial
-   Enhance algorithm for creating the desired sex ratio in groups.

# nprcmanager 0.5.27 (20190713)
-   Added to interactive tutorial
-   Minor corrections of function documentation
-   Moved _updateProgress_ parameter to end of list for __groupAddAssign()__.
  
# nprcmanager 0.5.26 (20190707)
-   Updated and corrected _\_software_development.Rmd_
-   Corrected summary statistics descriptions
-   Added expectConfigFile argument to __getSiteInfo()__ and associated unit 
    test to allow user to avoid a warning when configuration file is not 
    expected to be present.
  

# nprcmanager 0.5.25 (20190701)
-   Removed animals with exit dates from pyramid plots
-   Added ability to retain novel column names
-   Increased the number of column names understood for display in pedigree
    browser.

# nprcmanager 0.5.24 (20190630)
-   Renamed resetPopulation to setPopulation
-   Added sections to interactive_use_tutorial

# nprcmanager 0.5.23 (20190624)
-   Added weak unit test for getGenotypes function

# nprcmanager 0.5.22 (20190624)
-   Corrected and augmented unit tests for print_summary_nprcmanagGV and summary.nprcmanagGV

# nprcmanager 0.5.21 (20190624)
-   Added unit tests for print_summary_nprcmanagGV and summary.nprcmanagGV

# nprcmanager 0.5.20 (20190622)
-   Added unit test for getPedigree.

# nprcmanager 0.5.19 (20190622)
-   Replaced examplePedigree which I an failed to obfuscate with an obfuscated version
-   Added the ability to retrieve the map of original IDs to the new aliases to 
    obfuscatePed.

# nprcmanager 0.5.18 (20190622)
-   Replaced actual unpublished pedigree objects with obfuscated pedigree objects 
    so they can be shared
-   Updated unit tests that were dependent on replaced pedigree objects

# nprcmanager 0.5.17 (20190619)
-   Removed old pedigree files in preparation for new custom built 
    demonstration pedigrees
-   Removed old, no longer used logos

# nprcmanager 0.5.16 (20190615)
-   Added functions used to obfuscate pedigrees. This changes the IDs, all 
    dates and age calculations while maintaining internal relational 
    consistency (parent IDs correspond) and date, though different are
    similar.
    
# nprcmanager 0.5.15 (20190602)
-   Added ability to create an example pedigree file using the 
    __examplePedigree__ data structure.
-   Added __summary.nprcmanagGV__ and __print.summary.nprcmangGV__ functions
-   Added description of age-sex pyramid plot to the _summary of major functions_.

# nprcmanager 0.5.14 (20190518)
-   Added ability to use Excel files as input
    -    Added getGenotypes, getPedigree, getBreederPed, 
         readExcelPOSIXToCharacter,
    -    Added selection of Excel or Text file to uitpInput.R and modified 
         other aspects to separate out the delimiter selection logic.
    -    Default file type is Excel.
    -    If a user selects and Excel file and an Excel file is detected, all
         file type and delimiter selections are ignored and the Excel file
         is used and no error or warning is given.
         
-   Improved checkRequiredCols, toCharacter and getDatedFileName functions
-   Exported set_seed. This will be moved into rmsutilityr
-   Removed erroneous toCharacter documentation
-   Added set_seed
    -    Tried unsuccessfuly to use the RNGkind function and the sample.kind
         argument to set.seed, but found neither existed prior to R 3.6.
    -    Created a R version sensitive version of set_seed that duplicates
         the pre-R version 3.6 set.seed function. This is only useful for
         creating data structures for testing purposes and should not be used
         to set seeds for large simulations

# nprcmanager 0.5.13 (20190508)
-   Updated unit tests that were using set.seed to use a R version sensitive
    set.seed wrapper.
    
# nprcmanager 0.5.12 (20190507)
-   Updated nprcmanager.R to add __Pedigree Testing__ and __Plotting__ function
    lists.

# nprcmanager 0.5.11 (20190430)
-   Changed wording and format above Suspicious Parent table in ErrorTab
-   Removed row label from Suspicious Parent table
-   Updated meeting notes

# nprcmanager 0.5.10 (20190428)
-   Corrected roxygen2 comment "@export" in getAnimalsWithHighKinship(). 
-   Added unit test for fillGroupMembersWithSexRatio()

# nprcmanager 0.5.09 (20190428)
-   Corrected bug where parents with suspicious dates were not being reported.
-   Improved display of parents with suspicious dates by outputing HTML table
    to the ErrorTab.

# nprcmanager 0.5.08 (20190418)
-   Minor rewording of option label on breeding group formation tab

# nprcmanager 0.5.07 (20190408)
-   Rearranged and reformatted breeding group formation tab

# nprcmanager 0.5.06 (20190407)
-   Changed spelling of gu.iter and gu.thresh to guIter and guThresh

# nprcmanager 0.5.05 (20190406)
-   Fixed all but one bug associated with having multiple dynamically generated
    seed animal groups.
-   Added global definition of MAXGROUPS, which is current set as 10 and allows 
    up to six seed animal groups.
-   Corrected test_fillBins, which was erroneously using a current date instead 
    of a fixed date for calculating age.
    
# nprcmanager 0.5.04 (20190225)
-   Adding ability to have up to six seed animal groups.
-   Added conditional appearance of Make Groups action button that is 
    dependent on the user having select on of the optional group formation
    workflows.
    
# nprcmanager 0.5.03 (20190215)
-   Adding new version of breeding group formation UI and related server
    code.
    
# nprcmanager 0.5.02 (20190103)
-   Added ability to specify sex ratio in increments of 0.5 (Female/Male) 
    from 0.5 to 10 in increments of 0.5.
    
# nprcmanager 0.5.01 (20181230)
-   Correction of some bugs in harem creation and provided additional
    unit tests for harem creation to prevent regression.
    
# nprcmanager 0.5.00 (20181228)
-   First draft with harem group creation working.
    -   Fails if more than one potential sire (male and at least of minimum 
        age) is in the current group.
    -   Fails if there are insufficient males to have one per breeding group
        being formed.
    -   Requires the user to provide males in the candidate set that are 
        appropriate for breeding as the current code does not check to 
        ensure the animals are still alive. This could easily be added.
    -   Males are selected for each group randomly at each iteration just
        as are all other members. The only difference betweeen animal 
        selection for harems is that sex is part of the selection process.
    -   This required the creation of a few functions and modification of 
        others. Unit tests were updated to reflect changes, but not additions.
        New unit tests are needed.
    -   The format of the breeding group creation page must be improved.
    -   The changes made and the new unit tests will serve to simplify adding
        the sex ratio criterion to breeding group formation.
        
# nprcmanager 0.4.23 (20181226)
-   Added code to detect LabKey connection failure and report it on an Error tab

# nprcmanager 0.4.22 (20181224)
-   Minor text changes to Input tab. Refactored groupAddAssign function to
    have a function create the return list.
    
# nprcmanager 0.4.20 (20181222)
-   Refactor of __groupAddAssign__ function by extracting much of the function
    into separate functions. One such function, __fillGroupMembers__ isolates
    the group formation code to allow adding the ability to satisfy sex ratio
    requirements and harem creation.
    
# nprcmanager 0.4.19 (20181217) 
-   All minor interface changes
    -   Substituted hovertext for description of minimum parental age
    -   Added meeting notes for 20181210 meeting
    -   Changed label on button controling reading of pedigree information
    -   Updated logo
-   Added code of conduct file.
-   Corrected license text

# nprcmanager 0.4.18 (20181210)
-   Added unit test for removing animals added to pedigree because they are 
    unknown parents

# nprcmanager 0.4.17 (20181208)
-   Changed error reporting so as not to report as an error the wrong sex when 
    animals are added into the pedigree
    and appear as both a sire and dam without an ego record. 
    The error report now indicates these are both a sire and a dam. Done 20181208
-   Made a combined logo for Oregon and SNPRC. Have ONPRC on top using blue and
    green. Done 20181208
-   Additional unit 
    tests to cover all of the new functions created to handle the PEDSYS and
    military formated dates (YYYYMMDD) have been made. Done 20181112
-   Corrected breeding groups formation, which was including unknown animals that 
    had been added as placeholders for unknown parents. Done 20181119
-   Hardened LabKey code by trapping a bad base URL in the configuration file
    with a tryCatch function and send a message to the log file. This needs to be
    tested with a working LabKey system.
