---
title: "Genetic Management Software for Nonhuman Primates"
author: "R. Mark Sharp"
date: "11/20/2020"
output: 
  ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<!--
<div class="notes">
In March of 2017 I reached out to Amanda Vinson to request some new features
around LabKey integration. A few months later we began to collaborate on 
extending the capability of the genetic management software she and Michael
Raboin had created.

Present table

While doing this we added the ability to have different numbers of groups,
harems, and breeding groups of any specified sex ratio.
</div>
-->

## Update of Software From Vinson and Raboin (2015)
<!--Summary of software changes; publishing on CRAN. -->
Code Version | Files  | Lines | Code    | Documentation | Unit Tests
-------------| ------ | ----- | ------- | --------------|------------
Original Code |     8 | 3,621  | 1,927  |    0          |   0
1.0.3         |   293  | 13,776 |  775   |  4613         |  754

-   Online presence (https://rmsharp.github.io/nprcgenekeepr/)
    - Tutorials: Interactive and Shiny application
    - CRAN publication
    

## Immediate Future for nprcgenekeepr

-  Add ability to correct for false founders
   -   No parents
   -   One parent
-  Collaboration with primate centers
   -   LabKey integration
   -   Train users
   -   Improve tutorials based on feedback
-  Refactor User Interface Code

## Parent Exclusion Software
<!-- I need help with this in that I think I am seeing an error in the 
original code with microsatelites -->

  - Conversion of Java Scripts to R
  - Shiny Application
  - Integration into nprcgenekeepr

## Long Term Plans

-  Predictive modeling of breeding strategies via simulation

 - Suggestions?
    -  Database connectivity
       -  ARMS
       -  Oracle
    -  Group from common colony - assign kinship coefficients (matrix) 
       based on genetic data
    -  Tracking of individual alleles
    
## Interest Within Genetics and Genomics

-  What is currently available
-  Further development
<!-- Is there some feature you need to make it useful?
     Are there features that will make it more useful?
-->

## Acknowledgements
This work has been supported in part by NIH grants P51 RR13986 to the Southwest National Primate Research Center and P51 OD011092 to the Oregon National Primate Research Center.
