---
title: "Interactive Use of nprcmanager"
output: html_notebook
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = TRUE}
library(nprcmanager)
library(ggplot2)
library(knitr)

## You can use a file browser
#pedigreeFile <- file.choose()
## or you will have to change this to point to a pedigree file that you have
pedigreeFile <- "../inst/extdata/baboon_breeders_qc_ped.csv"

sep <- ","
minParentAge <- 0
breederPedCsv <- read.table(pedigreeFile, sep = sep, header = TRUE, stringsAsFactors = FALSE)
breederPed <- qcStudbook(breederPedCsv, minParentAge)
ped <- resetPopulation(breederPed, NULL)
probands <- ped$id[ped$population]
ped <- trimPedigree(probands, ped, removeUninformative = FALSE,
                    addBackParents = FALSE)
geneticValue <- reportGV(ped, gu.iter = 500,
                         gu.thresh = 3,
                         byID = TRUE,
                         updateProgress = NULL)
rpt <- geneticValue[["report"]]
g <- rpt
g$indivMeanKin <- round(g$indivMeanKin, 5)
g$zScores <- round(g$zScores, 2)
g$gu <- round(g$gu, 5)
g <- toCharacter(g)
names(g) <- headerDisplayNames(names(g))
knitr::kable(g[1:10, ]) # needs more work for display purposes.
gva <- g
kmat <- geneticValue[["kinship"]]
f <- geneticValue[["total"]]
mf <- geneticValue[["maleFounders"]]
ff <- geneticValue[["femaleFounders"]]
fe <- geneticValue[["fe"]]
fg <- geneticValue[["fg"]]

mk <- rpt[, "indivMeanKin"]
gu <- rpt[, "gu"]
guBox <- ggplot(data.frame(gu = gu), aes(x = "", y = gu)) +
  geom_boxplot(
    color = "darkblue",
    fill = "lightblue",
    notch = TRUE,
    outlier.color = "red",
    outlier.shape = 1
  ) +
  theme_classic() + geom_jitter(width = 0.2) + coord_flip() +
  ylab("Score")  + ggtitle("Genetic Uniqueness")
print(guBox)

gu <- rpt[, "indivMeanKin"]
gu <- rpt[, "zScores"]
```

To use the __findLoops__ function run the following code and select a pedigree as your input
file that has a loop in it. I have used the example pedigree that comes with the software
_Example_Pedigree.csv_.

```{r findLoops}
##pedigreeFile <- file.choose() ## use example file
pedigreefile <- pedigreeFile <- "../inst/extdata/Example_Pedigree.csv"
examplePedigree_raw <- read.table(pedigreeFile, sep = ",", header = TRUE, 
                                   stringsAsFactors = FALSE)
examplePedigree <- qcStudbook(examplePedigree_raw, minParentAge = 0)
exampleTree <- createPedTree(examplePedigree)
exampleLoops <- findLoops(exampleTree)

```
You can count how many loops you have with the following codel
```{r countLoops}
length(exampleLoops[exampleLoops == TRUE])

```

You can list the first 10 sets of ids, sires and dams in loops with the following line of code:

```{r listLoops}

examplePedigree[exampleLoops == TRUE, c("id", "sire", "dam")][1:10, ]


```

