---
title: "Summary of Major Functions"
author: "R. Mark Sharp"
date: "10/2/2017"
output: html_document
---
## Summary of Major Functions

### Quality Control
Studbooks maintained by breeding colonies generally contain
information of varying quality. The quality control functions
of the toolkit check to ensure all animals listed as parents
have their own line entries, all parents have
the appropriate sex listed, no animals are
listed as both a sire and a dam, duplicate entries are removed, 
pedigree generation numbers are added,
and all dates are valid dates. 
In addition, exit dates are
added if possible and are consistant with other information such as 
departure dates and death dates. 
Current ages of animals that are still alive are added.

Parents with ages below a user selected threshold are identified.
A minimum parent age in years is set by the user
and is used to ensure each parent is at least that age on the birth date of
an offspring. 
The minimum parent age defaults to 2 years. 
This check is not performed for animals with missing birth dates.

Further quality control measures may be added later, such as
checking to ensure parents' birthdates precede their children's.

### Creation of Pedigree From a List of Potential Breeders and LabKey Integration

The user can enter a list of breeders in a CSV file that will be used to 
create a pedigree containing all direct relative (ancestors and descendents)
via the \code{labkey.selectRows} function within the \code{Rlabkey} package.

Two configuration files are needed to use the database features of nprcmanager
with LabKey. 
The first file is named **\_netrc** on Microsoft Windows operating systems and 
**.netrc** otherwise, allows the user to authenticate with LabKey through the 
LabKey API and is fully 
described by [LabKey documentation](https://www.labkey.org/Documentation/wiki-page.view?name=netrc)

The second file is named **\_nprcmanager_config** on Microsoft Windows 
operating systems and **.nprcmanager_config** otherwise and is the nprcmanager 
[configuration file](https://github.com/rmsharp/nprcmanager/blob/master/inst/extdata/example_nprcmanager_config)


### Genetic Value Analysis Reports
The Genetic Value Analysis is a ranking scheme developed at ONPRC to
indicate the relative breeding value of animals in the colony. The
scheme uses the mean kinship for each animal to indicate how
inter-related it is with the rest of the current breeding colony
members. Genome uniqueness is used to provide an indication of
whether or not an animal is likely to possess alleles at risk
of being lost from the colony. Under the scheme, animals with low
mean kinship or high genome uniqueness are ranked more highly.

### Breeding Group Formation
One of the goals in breeding group formation is to avoid the
potential for mating of closely related animals. Since behavioral
concerns and housing constraints will also be taken into account
in the group formation process, it is our goal to provide the largest
number of animals possible from a list of candidates that can be housed
together without risk of consanguineous mating. To that end, this
function uses information from the Genetic Value Analysis to search
for the largest combinations of animals that can be produced from
a list of candidates.
