<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Interactive Use of nprcmanager • nprcmanager</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><meta property="og:title" content="Interactive Use of nprcmanager">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">nprcmanager</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.5.26</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/Development_Plans.html">Development Plans</a>
    </li>
    <li>
      <a href="../../articles/interactive_use_tutorial_files/Interactive_Use_with_style_sheet.html">Genetic Colony Management with \pkg{nprcmanager}</a>
    </li>
    <li>
      <a href="../../articles/interactive_use_tutorial_files/interactive_use_tutorial.html">Interactive Use of nprcmanager</a>
    </li>
    <li>
      <a href="../../articles/manual.html">Genetic Management Tools Manual</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/rmsharp/nprcmanager">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Interactive Use of nprcmanager</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/rmsharp/nprcmanager/blob/master/vignettes/interactive_use_tutorial_files/interactive_use_tutorial.Rmd"><code>vignettes/interactive_use_tutorial_files/interactive_use_tutorial.Rmd</code></a></small>
      <div class="hidden name"><code>interactive_use_tutorial.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This tutorial demonstrates the major functions used within the Shiny application provided by the <strong>nprcmanager</strong> package and provides sufficient insight into those functions that they may be used independently.</p>
</div>
<div id="installation-and-help" class="section level2">
<h2 class="hasAnchor">
<a href="#installation-and-help" class="anchor"></a>Installation and Help</h2>
<p>You can install <strong>nprcmanager</strong> from github with:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"devtools"</span>)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2">devtools<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/devtools/topics/reexports">install_github</a></span>(<span class="st">"rmsharp/nprcmanager"</span>)</a></code></pre></div>
<p>All missing dependencies should be automatically installed.</p>
<p>You can get help from the <strong>R</strong> console with</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">?nprcmanager</a></code></pre></div>
<p>The help provided by this (<em>nprcmanager.R</em>) needs to be more complete and include links to the tutorials.</p>
</div>
<div id="reading-in-pedigrees" class="section level2">
<h2 class="hasAnchor">
<a href="#reading-in-pedigrees" class="anchor"></a>Reading in Pedigrees</h2>
<p>Pedigrees can be imported using either Excel worksheets or text files that contain all of the pedigree information or using either Excel worksheets or text files that contain a list of focal animals with the remainder of the pedigree information is pulled in through the LabKey API.</p>
<p>This tutorial will use a pedigree file that can be created using the <strong>makeExamplePedigreeFile</strong> function as shown below. The function <strong>makeExamplePedigreeFile</strong> both saves a file and returns the full path name to the saved file, which we are saving into the variable <em>pedigreeFile</em>. Note: the user will select where to store the file.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(nprcmanager)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">pedigreeFile &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/makeExamplePedigreeFile.html">makeExamplePedigreeFile</a></span>()</a></code></pre></div>
<p>This writes <em>ExamplePedigree.csv</em> to a place you select within your file system.</p>
<p>You use the file name provided by the <strong>makeExamplePedigreeFile</strong> function to tell <strong>read.table</strong> what file to read.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">breederPedCsv &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/read.table">read.table</a></span>(pedigreeFile, <span class="dt">sep =</span> <span class="st">","</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb4-2" data-line-number="2">                            <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p>Note the number of rows read. Each row represents an individual within the pedigree.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(breederPedCsv)</a></code></pre></div>
<pre><code>## [1] 3694</code></pre>
<p>The next step is to put the information read from the file into a pedigree object. This is done with the <strong>qcStudbook</strong> function, which examines the file contents and tests for common pedigree errors.</p>
<p>You can see the errors that can be detected by <strong>qcStudbook</strong> by returning the empty error list with <strong>getEmptyErrorLst()</strong>. We are not showing the output of the function call now because later in this tutorial we will explore errors in more depth.</p>
<p><strong>qcStudbook</strong> can take four arguments <em>sb</em>, <em>minParentAge</em> (in years), <em>reportChanges</em>, and <em>reportErrors</em>. However, all but <em>sb</em> have default values and only the <em>sb</em> argument is required.</p>
<p>It is prudent to ensure that parents are at least of breeding age, which is species specific. I have used a <em>minParentAge</em> of 2 years.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>Running the line of code below will create a warning if you do not have the <strong>nprcmanager</strong> configuration file in place. This file is only needed when the LabKey API is to be used. It is not required for this tutorial.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">breederPed &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/qcStudbook.html">qcStudbook</a></span>(breederPedCsv, <span class="dt">minParentAge =</span> <span class="dv">2</span>)</a></code></pre></div>
<p>If <strong>qcStudbook</strong> reports an error, change the call by adding the <strong>reportErrors</strong> argument set to <strong>TRUE</strong> and examine the returned object. More on this is presented in the <strong>Pedigree Errors</strong> section.</p>
</div>
<div id="identifying-focal-animals" class="section level2">
<h2 class="hasAnchor">
<a href="#identifying-focal-animals" class="anchor"></a>Identifying Focal Animals</h2>
<p>You may want to focus your work on a <em>focal</em> group of animals. This can be done by reading in a list of animal IDs that make up the <em>focal</em> group and use that list to update the pedigree. Alternatively you can created a list of animal IDs based on criteria you have selected.</p>
<p>For example, to select living animals at the facility with at least one parent, the following can be used.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">focalAnimals &lt;-<span class="st"> </span>breederPed<span class="op">$</span>id[<span class="op">!</span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>sire) <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>dam)) <span class="op">&amp;</span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="st">                                </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>exit)]</a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(<span class="kw">stri_c</span>(<span class="st">"There are "</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(focalAnimals), <span class="st">" animals in the vector _focalAnimals_."</span>))</a></code></pre></div>
<p>[1] “There are 327 animals in the vector <em>focalAnimals</em>.”</p>
<p>As can be seen, these animals have at least one parent and have not left the facility.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">breederPed[breederPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"id"</span>, <span class="st">"sire"</span>, <span class="st">"dam"</span>, <span class="st">"exit"</span>)][<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]</a></code></pre></div>
<pre><code>##          id   sire    dam exit
## 1669 01QRQ4 VDBGDP TH7HTY &lt;NA&gt;
## 1743 CLSVU6 ULV9M7 SUFWJI &lt;NA&gt;
## 1887 1SPLS8 U9APLW 142GKP &lt;NA&gt;
## 1934 5IAFMK U4YSS5 WVE6Y4 &lt;NA&gt;
## 2072 HLQ9SY UI3RFL VEWC1E &lt;NA&gt;
## 2234 XFWVVX U3MFSZ L4LM1F &lt;NA&gt;
## 2337 6X6BG9 ENI6HX IUF0HC &lt;NA&gt;
## 2377 B228Q6 UEUIRJ CBSIAA &lt;NA&gt;
## 2378 B2CKHA ENI6HX WBFBR5 &lt;NA&gt;
## 2383 BCJJKN UA379T JPVAT3 &lt;NA&gt;</code></pre>
<p>We indicate that these are the animals of interest by using the <strong>setPopulation</strong> function. This function simply sets a column named <em>population</em><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> to the logical value of <strong>TRUE</strong> if the row represents an animal in the list and <strong>FALSE</strong> otherwise.</p>
<p>The first line of code below sets the <em>population</em> column and the second counts the number of rows where the value was set to <strong>TRUE</strong>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">breederPed &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/setPopulation.html">setPopulation</a></span>(<span class="dt">ped =</span> breederPed, <span class="dt">ids =</span> focalAnimals)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(breederPed[breederPed<span class="op">$</span>population, ])</a></code></pre></div>
<pre><code>## [1] 327</code></pre>
<p>The IDs used to populate the <em>population</em> flag can be used to trim the pedigree so that it contains only those individuals who are in the ID list or are ancestors of those individuals.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">trimmedPed &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/trimPedigree.html">trimPedigree</a></span>(focalAnimals, breederPed)</a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(breederPed); <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(trimmedPed)</a></code></pre></div>
<pre><code>## [1] 3694</code></pre>
<pre><code>## [1] 704</code></pre>
<p>The <strong>trimPedigree</strong> function has the ability to remove those ancestors that do not contribute genetic information. Uninformative founders are those individuals who are parents of only one individual and who have no parental information. (<em>Currently genotypic information is ignored by <strong>trimPedigree</strong></em>).</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">trimmedPedInformative &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/trimPedigree.html">trimPedigree</a></span>(focalAnimals, breederPed,</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">                                      <span class="dt">removeUninformative =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb16-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(trimmedPedInformative)</a></code></pre></div>
<pre><code>## [1] 509</code></pre>
<p>We can find all of the animals that are in the trimmed pedigree but are not focal animals.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">nonfocalInTrimmedPed &lt;-<span class="st"> </span>trimmedPed<span class="op">$</span>id[<span class="op">!</span>trimmedPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals]</a>
<a class="sourceLine" id="cb18-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(nonfocalInTrimmedPed)</a></code></pre></div>
<pre><code>## [1] 377</code></pre>
<p>We can see which of these 377 are and are not parents. We will first make sure we have all of the parents by getting our list of parents from the entire pedigree. We then demonstrate that they are all in the trimmed pedigree.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">allFocalParents &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(breederPed<span class="op">$</span>sire[breederPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals], </a>
<a class="sourceLine" id="cb20-2" data-line-number="2">                       breederPed<span class="op">$</span>dam[breederPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals])</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">trimmedFocalParents &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(trimmedPed<span class="op">$</span>sire[trimmedPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals], </a>
<a class="sourceLine" id="cb20-4" data-line-number="4">                       trimmedPed<span class="op">$</span>dam[trimmedPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>focalAnimals])</a>
<a class="sourceLine" id="cb20-5" data-line-number="5"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/all.equal">all.equal</a></span>(allFocalParents, trimmedFocalParents)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>However, not all of the animals in the trimmed pedigree are either the focal animals or their parents.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">notFocalNotParent &lt;-<span class="st"> </span>trimmedPed<span class="op">$</span>id[<span class="op">!</span>trimmedPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(focalAnimals, allFocalParents)]</a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(notFocalNotParent)</a></code></pre></div>
<pre><code>## [1] 187</code></pre>
<p>Since the trimming process is supposed to retain the focal animals and their ancestors, we will leave it as an exercise for you to demonstrate that at least some of the remaining animals are grandparents of the focal animals. <em>Hint: there are 490 grandparents in both the trimmed and the complete pedigree</em>.</p>
<p>As you can see from the number of rows in the full pedigree (3694) versus the trimmed pedigree (704), trimmed pedigrees can be much smaller. Of the additional 377 animals, 182 provide genetic information while the others (195) are genetically uninformative.</p>
<p>As is shown below only 4 (0ZX29Q, 1QBKW9, 5PWJ0G, and Y3CJ5A) living animals are still in the colony but are not in the trimmed pedigree.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">unknownBirth &lt;-<span class="st"> </span>breederPed<span class="op">$</span>id[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>birth)]</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">knownExit &lt;-<span class="st"> </span>breederPed<span class="op">$</span>id[ <span class="op">!</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>exit)]</a>
<a class="sourceLine" id="cb24-3" data-line-number="3">unknownBirthKnownExit &lt;-<span class="st"> </span>breederPed<span class="op">$</span>id[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>birth) <span class="op">|</span><span class="st"> </span><span class="op">!</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(breederPed<span class="op">$</span>exit)]</a>
<a class="sourceLine" id="cb24-4" data-line-number="4">knownPed &lt;-<span class="st"> </span>breederPed[<span class="op">!</span>breederPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>unknownBirthKnownExit, ]</a>
<a class="sourceLine" id="cb24-5" data-line-number="5">otherIds &lt;-<span class="st"> </span>knownPed<span class="op">$</span>id[<span class="op">!</span>knownPed<span class="op">$</span>id <span class="op">%in%</span><span class="st"> </span>trimmedPed<span class="op">$</span>id[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(trimmedPed<span class="op">$</span>exit)]]</a>
<a class="sourceLine" id="cb24-6" data-line-number="6"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(<span class="kw">stri_c</span>(<span class="st">"The living animal in the pedigree that are not in the trimmed "</span>,</a>
<a class="sourceLine" id="cb24-7" data-line-number="7">             <span class="st">"pedigree are "</span>, <span class="kw">get_and_or_list</span>(otherIds), <span class="st">"."</span>))</a></code></pre></div>
<p>[1] “The living animal in the pedigree that are not in the trimmed pedigree are 0ZX29Q, 1QBKW9, 5PWJ0G, and Y3CJ5A.”</p>
</div>
<div id="age-sex-pyramid-plot" class="section level2">
<h2 class="hasAnchor">
<a href="#age-sex-pyramid-plot" class="anchor"></a>Age Sex Pyramid Plot</h2>
<p>You can examine the population structure using an age-sex pyramid plot with a single function. We will limit our view to just the focal animals and their living relatives. This is appropriate for colony management because in addition to the genetic diversity we seek, we have to remain cognacent of the age and sex distributions within the colonies we manage.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw"><a href="../../reference/getPyramidPlot.html">getPyramidPlot</a></span>(<span class="dt">ped =</span> trimmedPed[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(trimmedPed<span class="op">$</span>exit), ])</a></code></pre></div>
<p><img src="interactive_use_tutorial_files/figure-html/plot-focal-age-sex-pyramid-1.png" width="700"></p>
</div>
<div id="genetic-value-analysis" class="section level2">
<h2 class="hasAnchor">
<a href="#genetic-value-analysis" class="anchor"></a>Genetic Value Analysis</h2>
<p>Your genetic value analysis must be carefully performed. The next three commands set up the entire pedigree for analysis. The first of these three commands set all of the pedigree members to be part of the population of interest by setting the <em>population</em> column to <strong>TRUE</strong> for all individuals. Note that a new pedigree object (<strong>ped</strong>) is being created.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">ped &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/setPopulation.html">setPopulation</a></span>(breederPed, <span class="ot">NULL</span>)</a></code></pre></div>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">probands &lt;-<span class="st"> </span>ped<span class="op">$</span>id[ped<span class="op">$</span>population]</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">ped &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/trimPedigree.html">trimPedigree</a></span>(probands, ped, <span class="dt">removeUninformative =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb27-3" data-line-number="3">                    <span class="dt">addBackParents =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb27-4" data-line-number="4"></a>
<a class="sourceLine" id="cb27-5" data-line-number="5"><span class="co">## Need a brief discussion of iterations (guIter), threshold (guThresh),</span></a>
<a class="sourceLine" id="cb27-6" data-line-number="6"><span class="co">## and byID.</span></a>
<a class="sourceLine" id="cb27-7" data-line-number="7"></a>
<a class="sourceLine" id="cb27-8" data-line-number="8">geneticValue &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/reportGV.html">reportGV</a></span>(ped, <span class="dt">guIter =</span> <span class="dv">500</span>,</a>
<a class="sourceLine" id="cb27-9" data-line-number="9">                         <span class="dt">guThresh =</span> <span class="dv">3</span>,</a>
<a class="sourceLine" id="cb27-10" data-line-number="10">                         <span class="dt">byID =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb27-11" data-line-number="11">                         <span class="dt">updateProgress =</span> <span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb27-12" data-line-number="12"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(geneticValue)</a></code></pre></div>
<pre><code>## The genetic value report 
## Individuals in Pedigree: 3694 
## Male Founders: 141
## Female Founders: 122
## Total Founders: 263 
## Founder Equivalents: 241.84 
## Founder Genome Equivalents: 163.8 
## Live Offspring: 4052 
## High Value Individuals: 2961 
## Low Value Individuals: 733</code></pre>
<p>What happens if we limit our analysis to the trimmed pedigree? Remember that the trimmed pedigree still contains all of the genetic information that the full pedigree has for the focal animals.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">trimmedGeneticValue &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/reportGV.html">reportGV</a></span>(trimmedPed, <span class="dt">guIter =</span> <span class="dv">500</span>,</a>
<a class="sourceLine" id="cb29-2" data-line-number="2">                         <span class="dt">guThresh =</span> <span class="dv">3</span>,</a>
<a class="sourceLine" id="cb29-3" data-line-number="3">                         <span class="dt">byID =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb29-4" data-line-number="4">                         <span class="dt">updateProgress =</span> <span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb29-5" data-line-number="5"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(trimmedGeneticValue)</a></code></pre></div>
<pre><code>## The genetic value report 
## Individuals in Pedigree: 327 
## Male Founders: 3
## Female Founders: 17
## Total Founders: 20 
## Founder Equivalents: 109.67 
## Founder Genome Equivalents: 47.86 
## Live Offspring: 321 
## High Value Individuals: 233 
## Low Value Individuals: 94</code></pre>
<p>It is clear that limiting your analysis to the animals of interest reduces the effort required to examine the animals of interest.</p>
<div id="detailed-look-at-the-genetic-value-report-object" class="section level3">
<h3 class="hasAnchor">
<a href="#detailed-look-at-the-genetic-value-report-object" class="anchor"></a>Detailed look at the Genetic Value Report object</h3>
<p>The names of the object within the genetic value report object (<em>trimmedGeneticValue</em>) can be listed as shown in the next line of code.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(trimmedGeneticValue)</a></code></pre></div>
<pre><code>## [1] "report"         "kinship"        "gu"             "fe"            
## [5] "fg"             "maleFounders"   "femaleFounders" "total"</code></pre>
<p>The <em>report</em> object (an R dataframe) can in-turn be examined.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(trimmedGeneticValue<span class="op">$</span>report) <span class="co">## column names</span></a></code></pre></div>
<pre><code>##  [1] "id"              "sex"             "age"            
##  [4] "birth"           "exit"            "population"     
##  [7] "origin"          "indivMeanKin"    "zScores"        
## [10] "gu"              "totalOffspring"  "livingOffspring"
## [13] "value"           "rank"</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(trimmedGeneticValue<span class="op">$</span>report) <span class="co">## Number of rows</span></a></code></pre></div>
<pre><code>## [1] 327</code></pre>
<p>The report is more conveniently used as a separate object. The next section of code rounds some of the numerica values and converts all columns to characters for display as a table where only the first 10 lines are included.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">rpt &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"report"</span>]]</a>
<a class="sourceLine" id="cb37-2" data-line-number="2">rpt<span class="op">$</span>indivMeanKin &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(rpt<span class="op">$</span>indivMeanKin, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb37-3" data-line-number="3">rpt<span class="op">$</span>zScores &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(rpt<span class="op">$</span>zScores, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb37-4" data-line-number="4">rpt<span class="op">$</span>gu &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(rpt<span class="op">$</span>gu, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb37-5" data-line-number="5">rpt &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/toCharacter.html">toCharacter</a></span>(rpt)</a>
<a class="sourceLine" id="cb37-6" data-line-number="6"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(rpt) &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/headerDisplayNames.html">headerDisplayNames</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(rpt))</a>
<a class="sourceLine" id="cb37-7" data-line-number="7">knitr<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(rpt[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]) <span class="co"># needs more work for display purposes.</span></a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">Ego ID</th>
<th align="left">Sex</th>
<th align="right">Age (in years)</th>
<th align="left">Birth Date</th>
<th align="left">Exit Date</th>
<th align="left">Breeding Colony Member</th>
<th align="left">Origin</th>
<th align="right">Individual Mean Kinship</th>
<th align="right">Z-score (Mean Kinship)</th>
<th align="right">Genome Uniqueness (%)</th>
<th align="right">Total Offspring</th>
<th align="right">Living Offspring</th>
<th align="left">Value Designation</th>
<th align="right">Rank</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">CLSVU6</td>
<td align="left">F</td>
<td align="right">23.9</td>
<td align="left">1995-08-02</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00287</td>
<td align="right">-1.97</td>
<td align="right">88.6</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">High Value</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">KZM9RB</td>
<td align="left">M</td>
<td align="right">30.1</td>
<td align="left">1989-05-03</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00329</td>
<td align="right">-1.90</td>
<td align="right">86.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">1SPLS8</td>
<td align="left">F</td>
<td align="right">7.9</td>
<td align="left">2011-07-26</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00373</td>
<td align="right">-1.83</td>
<td align="right">79.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">WK89I9</td>
<td align="left">F</td>
<td align="right">21.1</td>
<td align="left">1998-05-26</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00582</td>
<td align="right">-1.49</td>
<td align="right">76.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">01QRQ4</td>
<td align="left">F</td>
<td align="right">18.2</td>
<td align="left">2001-04-04</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00373</td>
<td align="right">-1.83</td>
<td align="right">75.1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">8YP6PA</td>
<td align="left">M</td>
<td align="right">5.0</td>
<td align="left">2014-07-04</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00485</td>
<td align="right">-1.65</td>
<td align="right">74.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">IZDV8K</td>
<td align="left">M</td>
<td align="right">7.7</td>
<td align="left">2011-09-29</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00480</td>
<td align="right">-1.66</td>
<td align="right">73.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">3MMZD4</td>
<td align="left">M</td>
<td align="right">12.2</td>
<td align="left">2007-03-24</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00536</td>
<td align="right">-1.57</td>
<td align="right">72.4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">CHK1ZX</td>
<td align="left">F</td>
<td align="right">7.8</td>
<td align="left">2011-09-06</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00481</td>
<td align="right">-1.66</td>
<td align="right">69.6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">50D77I</td>
<td align="left">F</td>
<td align="right">20.1</td>
<td align="left">1999-05-08</td>
<td align="left">NA</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="right">0.00451</td>
<td align="right">-1.71</td>
<td align="right">68.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">High Value</td>
<td align="right">10</td>
</tr>
</tbody>
</table>
<p>We start the next lines of code by getting a fresh copy of the genetic value report since we changed all of the numeric values to characters in the last section to print the table. These lines demonstrate one way of extracting the component objects from the <em>genetic value</em> object.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">rpt &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"report"</span>]]</a>
<a class="sourceLine" id="cb38-2" data-line-number="2">kmat &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"kinship"</span>]]</a>
<a class="sourceLine" id="cb38-3" data-line-number="3">f &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"total"</span>]]</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">mf &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"maleFounders"</span>]]</a>
<a class="sourceLine" id="cb38-5" data-line-number="5">ff &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"femaleFounders"</span>]]</a>
<a class="sourceLine" id="cb38-6" data-line-number="6">fe &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"fe"</span>]]</a>
<a class="sourceLine" id="cb38-7" data-line-number="7">fg &lt;-<span class="st"> </span>trimmedGeneticValue[[<span class="st">"fg"</span>]]</a></code></pre></div>
<p>It is informative to examine the distribution of <em>genetic uniqueness</em>, <em>mean kinship</em>, and <em>z-scores</em> (normalized <em>mean kinship</em> values).</p>
<p>Creation of the boxplot for the <em>genetic uniqueness</em> values is shown below.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">gu &lt;-<span class="st"> </span>rpt[, <span class="st">"gu"</span>]</a>
<a class="sourceLine" id="cb39-2" data-line-number="2">guBox &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">gu =</span> gu), <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">""</span>, <span class="dt">y =</span> gu)) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_boxplot</span>(</a>
<a class="sourceLine" id="cb39-4" data-line-number="4">    <span class="dt">color =</span> <span class="st">"darkblue"</span>,</a>
<a class="sourceLine" id="cb39-5" data-line-number="5">    <span class="dt">fill =</span> <span class="st">"lightblue"</span>,</a>
<a class="sourceLine" id="cb39-6" data-line-number="6">    <span class="dt">notch =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb39-7" data-line-number="7">    <span class="dt">outlier.color =</span> <span class="st">"red"</span>,</a>
<a class="sourceLine" id="cb39-8" data-line-number="8">    <span class="dt">outlier.shape =</span> <span class="dv">1</span></a>
<a class="sourceLine" id="cb39-9" data-line-number="9">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-10" data-line-number="10"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb39-11" data-line-number="11"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">"Score"</span>)  <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">"Genetic Uniqueness"</span>)</a>
<a class="sourceLine" id="cb39-12" data-line-number="12"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(guBox)</a></code></pre></div>
<p><img src="interactive_use_tutorial_files/figure-html/genetic-uniqueness-boxplot-1.png" width="700"></p>
<p>Extraction of the individual <em>mean kinship</em> values and their corresponding z-scores is shown in the next code chunk.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">mk &lt;-<span class="st"> </span>rpt[, <span class="st">"indivMeanKin"</span>]</a>
<a class="sourceLine" id="cb40-2" data-line-number="2">zs &lt;-<span class="st"> </span>rpt[, <span class="st">"zScores"</span>]</a></code></pre></div>
<p>Creation of boxplots for the <em>mean kinship</em> and <em>z-scores</em> is left as an exercise.</p>
</div>
</div>
<div id="breeding-group-formation" class="section level2">
<h2 class="hasAnchor">
<a href="#breeding-group-formation" class="anchor"></a>Breeding Group Formation</h2>
</div>
<div id="pedigree-errors" class="section level2">
<h2 class="hasAnchor">
<a href="#pedigree-errors" class="anchor"></a>Pedigree Errors</h2>
<p>As stated earlier you can see which types of errors are detected by <em>qcStudbook</em> by looking at names returned by <em>getEmptyErrorLst()</em> as shown below.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(<span class="kw"><a href="../../reference/getEmptyErrorLst.html">getEmptyErrorLst</a></span>())</a></code></pre></div>
<pre><code>## [1] "failedDatabaseConnection" "missingColumns"          
## [3] "invalidDateRows"          "suspiciousParents"       
## [5] "femaleSires"              "maleDams"                
## [7] "sireAndDam"               "duplicateIds"            
## [9] "changedCols"</code></pre>
<p>Each is defined below.</p>
<table class="table">
<thead><tr class="header">
<th align="left">Error</th>
<th align="left">Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">failedDatabaseConnection</td>
<td align="left">Database connection failed: configuration or permissions are invalid</td>
</tr>
<tr class="even">
<td align="left">missingColumns</td>
<td align="left">Columns that must be within the pedigree file are missing.</td>
</tr>
<tr class="odd">
<td align="left">invalidDateRows</td>
<td align="left">Values, which are supposed to be dates, cannot be interpreted as a date.</td>
</tr>
<tr class="even">
<td align="left">suspiciousParents</td>
<td align="left">Parents were too young on the date of birth of to have been the parent.</td>
</tr>
<tr class="odd">
<td align="left">femaleSires</td>
<td align="left">Individuals listed as female or hemaphroditic and as a sire.</td>
</tr>
<tr class="even">
<td align="left">maleDams</td>
<td align="left">Individuals are listed as male and as a dam.</td>
</tr>
<tr class="odd">
<td align="left">sireAndDam</td>
<td align="left">Individuals who are listed as both a sire and a dam.</td>
</tr>
<tr class="even">
<td align="left">duplicateIds</td>
<td align="left">IDs listed more than once.</td>
</tr>
<tr class="odd">
<td align="left">changedCols</td>
<td align="left">Columns that have been changed to conform to internal naming conventions and what they were changed to.</td>
</tr>
</tbody>
</table>
<div id="introducing-errors-into-a-pedigree" class="section level3">
<h3 class="hasAnchor">
<a href="#introducing-errors-into-a-pedigree" class="anchor"></a>Introducing Errors Into A Pedigree</h3>
<p>In order to discuss pedigree error detection, we are going to use a very small imaginary pedigree listed below. Note the birth dates of ego_id <em>o4</em> (2006-04-13) and the purported sire (2006-06-19). Obviously either a date or an ID is incorrect.</p>
<p>This is the pedigree.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">nprcmanager<span class="op">::</span>pedOne</a></code></pre></div>
<pre><code>##   ego_id si re dam_id sex birth_date
## 1     s1  &lt;NA&gt;   &lt;NA&gt;   F 2000-07-18
## 2     d1  &lt;NA&gt;   &lt;NA&gt;   M 2003-04-13
## 3     s2  &lt;NA&gt;   &lt;NA&gt;   M 2006-06-19
## 4     d2  &lt;NA&gt;   &lt;NA&gt;   F 2015-09-16
## 5     o1    s1     d1   F 2015-02-04
## 6     o2    s1     d2   F 2009-03-17
## 7     o3    s2     d2   F 2012-04-11
## 8     o4    s2     d2   M 2006-04-13</code></pre>
<p>If we examine this pedigree file, we are going to get an error message. In additions since I do not have a valid database configuration file so we will get a warning about that.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">pedOne &lt;-<span class="st"> </span>nprcmanager<span class="op">::</span>pedOne <span class="co"># put it in the local environment</span></a>
<a class="sourceLine" id="cb45-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(<span class="kw"><a href="../../reference/qcStudbook.html">qcStudbook</a></span>(pedOne, <span class="dt">minParentAge =</span> <span class="dv">0</span>))</a></code></pre></div>
<pre><code>## Error in qcStudbook(pedOne, minParentAge = 0): Parents with low age at birth of offspring are listed in ~/lowParentAge.csv.</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/warnings">warnings</a></span>()</a></code></pre></div>
<p>We can turn off this warning by telling <strong>qcStudbook</strong> not to expect a file ## Genetic Loops</p>
<p>To use the <strong>findLoops</strong> function run the following code and select a pedigree as your input file that has a loop in it. We are continuing to use the example pedigree that comes with the software <em>Example_Pedigree.csv</em>.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">exampleTree &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/createPedTree.html">createPedTree</a></span>(breederPed)</a>
<a class="sourceLine" id="cb48-2" data-line-number="2">exampleLoops &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/findLoops.html">findLoops</a></span>(exampleTree)</a></code></pre></div>
<p>You can count how many loops you have with the following code.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(exampleLoops[exampleLoops <span class="op">==</span><span class="st"> </span><span class="ot">TRUE</span>])</a></code></pre></div>
<pre><code>## [1] 145</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">nLoops &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/countLoops.html">countLoops</a></span>(exampleLoops, exampleTree)</a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/unlist">unlist</a></span>(nLoops[nLoops <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>]))</a></code></pre></div>
<pre><code>## [1] 258</code></pre>
<p>You can list the first 10 sets of ids, sires and dams in loops with the following line of code:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">examplePedigree[exampleLoops <span class="op">==</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"id"</span>, <span class="st">"sire"</span>, <span class="st">"dam"</span>)][<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]</a></code></pre></div>
<pre><code>##          id   sire    dam
## 2519 V49H3Y UFI88T 9T7Y2Z
## 2572 61FUGE UDQ5WC GL88CF
## 2695 LWJ3A5 KZM9RB GCBYDW
## 2722 RNQU14 H2RDE2 DKIM6U
## 2752 L9M1DC 3PU50K WFQENR
## 2755 Q8U9LB 3PU50K CLSVU6
## 2905 FVJ14K UXC40T L5VC2M
## 2922 531HAC UMV4BE 5DIPZN
## 2924 85ESBB UQFY9C Q2RK1E
## 2941 0VLW56 6KPKH7 MMEHXV</code></pre>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>Setting the <em>minParentAge</em> to 3.5 and above will cause an error along with the creation of a file <em>~/lowParentAge.csv</em> that will list the parents with low age at the birth of an offspring.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>The <em>population</em> column is created and added to the pedigree object if it does not already exist.<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>All animals within the colony have a known birth date.<a href="#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#installation-and-help">Installation and Help</a></li>
      <li><a href="#reading-in-pedigrees">Reading in Pedigrees</a></li>
      <li><a href="#identifying-focal-animals">Identifying Focal Animals</a></li>
      <li><a href="#age-sex-pyramid-plot">Age Sex Pyramid Plot</a></li>
      <li><a href="#genetic-value-analysis">Genetic Value Analysis</a></li>
      <li><a href="#breeding-group-formation">Breeding Group Formation</a></li>
      <li><a href="#pedigree-errors">Pedigree Errors</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Michael Raboin, R. Mark Sharp.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
