context("convertAncestry")
library(testthat)
original <- c("m", "male", "1", "MALE", "M", "F", "f", "female", "FemAle", "U",
              "Unknown", "H", "hermaphrodite", "U", "Unknown", "3", "4")
ancestry <- convertSexCodes(original)
test_that("convertAncestry makes correct transformations", {
  expect_true(is.factor(ancestry))
  ancestry <- as.character(ancestry)
  expect_equal(ancestry[1], "M")
  expect_equal(ancestry[2], "M")
  expect_equal(ancestry[3], "M")
  expect_equal(ancestry[4], "M")
  expect_equal(ancestry[5], "M")
  expect_equal(ancestry[6], "F")
  expect_equal(ancestry[7], "F")
  expect_equal(ancestry[8], "F")
  expect_equal(ancestry[9], "F")
  expect_equal(ancestry[10], "U")
  expect_equal(ancestry[11], "U")
  expect_equal(ancestry[12], "U")
  expect_equal(ancestry[13], "U")
  expect_equal(ancestry[14], "U")
  expect_equal(ancestry[15], "U")
  expect_equal(ancestry[16], "U")
  expect_equal(ancestry[17], "U")
  ancestry <- convertSexCodes(original, ignoreHerm = FALSE)
  ancestry <- as.character(ancestry)
  expect_equal(ancestry[12], "H")
  expect_equal(ancestry[13], "H")
  expect_equal(ancestry[13], "H")
  expect_equal(ancestry[17], "H")
})
