#' Get the direct ancestors of selected animals
#'
#' Gets direct ancestors from labkey \code{study} schema and \code{demographics}
#' table.
#'
#' @return dataframe with pedigree structure having all of the direct ancestors
#' for the Ids provided.
#' @param ids character vector with Ids.
#' @param unrelatedParents logical vector when \code{FALSE} the unrelated
#' parents of offspring do not get a record as an ego; when \code{TRUE}
#' a place holder record where parent (\code{sire},
#' \code{dam}) IDs are set to \code{NA}.
#'
#' @import futile.logger
#' @importFrom stringi stri_c
#' @export
getLkDirectRelatives <- function(ids, unrelatedParents = FALSE) {
  siteInfo <- getSiteInfo()
  colSet <- siteInfo$lkPedColumns
  source <- " generated by getDemographics in getLkDirectRelatives: "
  pedSourceDf <- tryCatch(getDemographics(colSelect = colSet),
                          warning = function(cond) {
                            flog.debug(stri_c("Warning", source, cond),
                                       name = "nprcmanager")
                            return(NULL)},
                          error = function(cond) {
                            flog.debug(stri_c("Error", source, cond),
                                       name = "nprcmanager")
                            return(NULL)}
  )
  names(pedSourceDf) <- siteInfo$mapPedColumns
  parents <- ids
  offspring <- ids
  len <- length(parents)
  relativesDf <- pedSourceDf[pedSourceDf$id %in% ids, ]
  while (len > 0) {
    parents <- getParents(pedSourceDf, parents)
    offspring <- getOffspring(pedSourceDf, offspring)
    len <- length(parents) + length(offspring)
    if (len > 0) {
      if (length(parents) > 0) {
        relativesDf <- rbind(relativesDf,
                             pedSourceDf[pedSourceDf$id %in% parents, ],
                             stringsAsFactors = FALSE)
      }
      if (length(offspring) > 0) {
        relativesDf <- rbind(relativesDf,
                             pedSourceDf[pedSourceDf$id %in% offspring, ],
                             stringsAsFactors = FALSE)
      }
      relativesDf <- relativesDf[!duplicated(relativesDf$id), ]
    }
  }
  unrelated <- unique(c(
    relativesDf$sire[!relativesDf$sire %in% relativesDf$id],
    relativesDf$dam[!relativesDf$dam %in% relativesDf$id]))
  addIdRecords(ids = unrelated, fullPed = pedSourceDf, partialPed = relativesDf)
  # if (length(unrelated) > 0) {
  #   tempDf <- pedSourceDf[pedSourceDf$id %in% unrelated, ]
  #   tempDf$sire <- NA
  #   tempDf$dam <- NA
  #   relativesDf <- rbind(relativesDf,
  #                        tempDf,
  #                        stringsAsFactors = FALSE)
  # }
  # relativesDf[!duplicated(relativesDf$id), ]
}
